### ISSUE TITLE
java.lang.NullPointerException on login

### ISSUE THREAD

**Issue by bluelightning32** [TerminatorNL/Tiquality#27]
My server was working fine, then players started reporting an internal server error on login. It effects all players. I didn't change anything on the server when the error reports started.

Modpack: Manufactio version 0.95
Forge: forge-1.12.2-14.23.5.2822-universal
Tiquality: Tiquality-FAT-1.12.2-GAMMA-1.3.0

```
[21:17:31] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /192.168.15.1:58790
java.lang.NullPointerException: null
        at cf.terminator.tiquality.util.PersistentData.getCompoundTag(PersistentData.java:80) ~[PersistentData.class:?]
        at cf.terminator.tiquality.tracking.TrackerHolder.getTrackerHolder(TrackerHolder.java:99) ~[TrackerHolder.class:?]
        at net.minecraft.world.chunk.Chunk.tiquality_loadNBT(Chunk.java:2867) ~[axw.class:?]
        at cf.terminator.tiquality.monitor.ChunkLoadMonitor.onNBTLoad(ChunkLoadMonitor.java:37) ~[ChunkLoadMonitor.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_755_ChunkLoadMonitor_onNBTLoad_Load.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:103) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89) ~[on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135) ~[on.class:?]
        at net.minecraft.world.World.getChunk(World.java:310) ~[amu.class:?]
        at net.minecraft.world.World.getChunk(World.java:305) ~[amu.class:?]
        at net.minecraft.world.World.getTopSolidOrLiquidBlock(World.java:1619) ~[amu.class:?]
        at net.minecraft.world.WorldProvider.getRandomizedSpawnPoint(WorldProvider.java:350) ~[aym.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:161) ~[oq.class:?]
        at net.minecraft.server.management.PlayerList.createPlayerForUser(PlayerList.java:504) ~[pl.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:135) ~[pc.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:63) ~[pc.class:?]
        at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[21:17:31] [Server thread/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: com.mojang.authlib.GameProfile@7f31a874[id=2e15e144-51b9-4f4b-a495-74dc0765a409,name=bluelightning32,properties={textures=[com.mojang.authlib.properties.Property@3c5c162e]},legacy=false] (/192.168.15.1:58790) lost connection: Internal server error
```

Full log: https://gist.github.com/bluelightning32/888d692c54e0139dc4c6b9e0addd9529

**Comment by bluelightning32** [comment]
I tried removing Tiquality and restarting the server. I can login then.

**Comment by TerminatorNL** [comment]
This is fixed in my local codebase, I'm reworking the world save mechanism to allow for Tiquality removal without data loss. After that's been updated, I'll push a new official release. Here's a temporary jar you can use if you _really_ need Tiquality right now.

Please note that because Tiquality had been removed, all your data is lost and people will have to re-claim their bases. This is why I am working on re-designing the saving mechanism to prevent data loss

[UNZIP_ME_Tiquality-THIN-1.12.2-GAMMA-1.3.1.zip](https://github.com/TerminatorNL/Tiquality/files/3201996/UNZIP_ME_Tiquality-THIN-1.12.2-GAMMA-1.3.1.zip)
