### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by bigenergy** [TerminatorNL/Tiquality#4]
Tiquality-THIN-1.12.2-BETA-0.7.2
https://pastebin.com/k7svEuLv

**Comment by TerminatorNL** [comment]
Can you provide me the full server log?

**Comment by bigenergy** [comment]
> Can you provide me the full server log?

[debug.log](https://github.com/TerminatorNL/Tiquality/files/2577879/debug.log)

**Comment by bigenergy** [comment]
Last (crash report -> https://pastebin.com/k7svEuLv)
[debug-last.txt](https://github.com/TerminatorNL/Tiquality/files/2577885/debug-last.txt)

**Comment by bigenergy** [comment]
in the first debug.log I had laggoogles installed, in the last debug-last.txt no

**Comment by TerminatorNL** [comment]
I have no idea why it does this. Are you able to reliably replicate this issue?

**Comment by bigenergy** [comment]
I don't even know how, but I'll try

**Comment by bigenergy** [comment]
I use /tq import_griefprevention

**Comment by bigenergy** [comment]
```
[21:52:57] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@2cdadcd:
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_181]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_181]
	at cf.terminator.tiquality.tracking.TrackerManager.foreach(TrackerManager.java:28) ~[TrackerManager.class:?]
	at cf.terminator.tiquality.tracking.TrackerManager.tickUntil(TrackerManager.java:44) ~[TrackerManager.class:?]
	at cf.terminator.tiquality.monitor.TickMaster.onServerTick(TickMaster.java:61) ~[TickMaster.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_833_TickMaster_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[21:52:57] [Server thread/ERROR] [FML]: Index: 29 Listeners:
[21:52:57] [Server thread/ERROR] [FML]: 0: HIGHEST
[21:52:57] [Server thread/ERROR] [FML]: 1: ASM: cf.terminator.tiquality.monitor.TPSMonitor@14b439e6 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 2: NORMAL
[21:52:57] [Server thread/ERROR] [FML]: 3: ASM: class crazypants.enderio.base.teleport.ChunkTicket onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 4: ASM: class crazypants.enderio.base.item.spawner.BrokenSpawnerHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 5: ASM: class crazypants.enderio.base.TileEntityEio onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 6: ASM: class crazypants.enderio.base.handler.ServerTickHandler onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 7: ASM: class blusunrize.immersiveengineering.common.blocks.BlockIETileProvider onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 8: ASM: net.minecraftforge.common.ForgeInternalHandler@6c466574 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 9: ASM: spongeforge onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 10: ASM: ic2.core.TickHandler@51512b9c onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 11: ASM: com.brandon3055.brandonscore.handlers.ProcessHandler@11e64cf3 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 12: ASM: noppes.npcs.ServerTickHandler@630d804 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 13: ASM: com.brandon3055.draconicevolution.handlers.DEEventHandler@766b1912 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 14: ASM: com.zeitheron.hammercore.internal.variables.VarEvents@45b84f57 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 15: ASM: com.zeitheron.thaumicadditions.utils.ThaumicScheduler@170e0679 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 16: ASM: com.zeitheron.hammercore.event.vanilla.TileHandler@6ed2bd7c serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 17: ASM: com.zeitheron.hammercore.internal.chunk.ChunkloadAPI@26a0cc93 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 18: ASM: com.zeitheron.hammercore.HammerCore@666666 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 19: ASM: cofh.thermaldynamics.util.TickHandler@5eba8b1 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 20: ASM: cf.terminator.tiquality.util.Scheduler@33812e75 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 21: ASM: codechicken.chunkloader.handler.ChunkLoaderEventHandler@c6b9def serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 22: ASM: com.enderio.core.common.util.Scheduler@29ad35e7 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 23: ASM: crazypants.enderio.base.init.CommonProxy$TickTimer@46387e9a onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 24: ASM: cf.terminator.tiquality.world.WorldHelper$SmearedAction@3f0b9b20 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 25: ASM: Block{null} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 26: ASM: noppes.npcs.ScriptPlayerEventHandler@7e319f25 forgeEntity(Lnet/minecraftforge/fml/common/eventhandler/Event;)V
[21:52:57] [Server thread/ERROR] [FML]: 27: LOWEST
[21:52:57] [Server thread/ERROR] [FML]: 28: ASM: class codechicken.lib.internal.CCLLog onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [FML]: 29: ASM: cf.terminator.tiquality.monitor.TickMaster@3cef84c9 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:52:57] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_181]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_181]
	at cf.terminator.tiquality.tracking.TrackerManager.foreach(TrackerManager.java:28) ~[TrackerManager.class:?]
	at cf.terminator.tiquality.tracking.TrackerManager.tickUntil(TrackerManager.java:44) ~[TrackerManager.class:?]
	at cf.terminator.tiquality.monitor.TickMaster.onServerTick(TickMaster.java:61) ~[TickMaster.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_833_TickMaster_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:687) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:641) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by Mr-Krab** [comment]
I will add.
https://pastebin.com/7T0gvNfV
https://pastebin.com/zTTPD65v

**Comment by bigenergy** [comment]
@TerminatorNL How's it going?

**Comment by bigenergy** [comment]
@TerminatorNL Please fix it, this mod really helps my server. I can't find an alternative :(

**Comment by Mr-Krab** [comment]
@bigenergy  I think it will not speed up the correction of the problem.

**Comment by TerminatorNL** [comment]
Sorry folks, this is not a straightforward fix and I don't have a lot of time to code. Like before, I will notify you if it's done.

**Comment by TerminatorNL** [comment]
Hey folks, let me know if version 1.12.2-BETA-0.8 works for you.

**Comment by TerminatorNL** [comment]
Download is up: https://minecraft.curseforge.com/projects/tiquality/files

Feel free to re-open this issue if the problem re-arises

**Comment by bigenergy** [comment]
Crash now, I use /tq import_griefprevention and get crash
Crash: https://pastebin.com/WVEsx0tg

Full log:
[2018-12-07-3.log](https://github.com/TerminatorNL/Tiquality/files/2658443/2018-12-07-3.log)

**Comment by bigenergy** [comment]
> Can you let me know if this solves your problem in about 2 days?

At first glance it works, I will test and let you know!

**Comment by bigenergy** [comment]
New crash
[crash-2018-12-10_11.35.31-server.txt](https://github.com/TerminatorNL/Tiquality/files/2662274/crash-2018-12-10_11.35.31-server.txt)

**Comment by TerminatorNL** [comment]
I made a new release. a4de72496653ab1b6458bf81459bb960d573dc01 should fix it

**Comment by bigenergy** [comment]
@TerminatorNL Good job, thanks! I'm testing it.
New error after /tq import_griefprevention

`[22:43:47] [Server thread/INFO] [nucleus]: Server ran the command: /tq import_griefprevention
[22:43:47] [Tiquality GP import thread/INFO] [tiquality]: Importing griefprevention claims...
[22:43:47] [Tiquality GP import thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Tiquality] Import started.
[22:43:47] [Tiquality GP import thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[22:43:47] [Tiquality GP import thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cf.terminator.tiquality.tracking.PlayerTracker.getOrCreatePlayerTrackerByProfile(PlayerTracker.java:46)
[22:43:47] [Tiquality GP import thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cf.terminator.tiquality.integration.griefprevention.GriefPreventionTracker.updatePlayers(GriefPreventionTracker.java:218)
[22:43:47] [Tiquality GP import thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cf.terminator.tiquality.integration.griefprevention.GriefPreventionTracker.<init>(GriefPreventionTracker.java:62)
[22:43:47] [Tiquality GP import thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cf.terminator.tiquality.integration.griefprevention.GriefPreventionHook.findOrGetTrackerByClaim(GriefPreventionHook.java:126)
[22:43:47] [Tiquality GP import thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cf.terminator.tiquality.integration.griefprevention.GriefPreventionHook.loadClaimsForcibly(GriefPreventionHook.java:66)
[22:43:47] [Tiquality GP import thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cf.terminator.tiquality.command.CommandExecutor$5.run(CommandExecutor.java:259)
[22:43:47] [Tiquality GP import thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[22:43:47] [Server thread/INFO] [tiquality]: Importing: dusted at DIM=0 X: -1254 Z: 3083
[22:43:47] [Server thread/INFO] [tiquality]: [Tiquality] Remaining: 12
[22:43:47] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Tiquality] Remaining: 12
[22:43:47] [Server thread/INFO] [tiquality]: Importing: dusted at DIM=0 X: -1317 Z: 2390
[22:43:47] [Server thread/INFO] [tiquality]: [Tiquality] Remaining: 11
[22:43:47] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Tiquality] Remaining: 11
[22:43:47] [Server thread/INFO] [tiquality]: Importing: edge at DIM=0 X: -2877 Z: 436
[22:43:47] [Server thread/INFO] [tiquality]: [Tiquality] Remaining: 10
[22:43:47] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Tiquality] Remaining: 10
[22:43:47] [Server thread/INFO] [tiquality]: Importing: alexcraza at DIM=0 X: 1760 Z: 2016
[22:43:48] [Server thread/INFO] [tiquality]: [Tiquality] Remaining: 9
[22:43:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Tiquality] Remaining: 9
[22:43:48] [Server thread/INFO] [tiquality]: Importing: vadimlvk at DIM=0 X: 100 Z: 3261
[22:43:48] [Server thread/INFO] [tiquality]: [Tiquality] Remaining: 8
[22:43:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Tiquality] Remaining: 8
[22:43:48] [Server thread/INFO] [tiquality]: Importing: medvedchuk at DIM=0 X: 320 Z: 2022
[22:43:48] [Server thread/INFO] [tiquality]: [Tiquality] Remaining: 7
[22:43:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Tiquality] Remaining: 7
[22:43:48] [Server thread/INFO] [tiquality]: Importing: d_a_medvedev at DIM=0 X: -2693 Z: 3068
[22:43:48] [Server thread/INFO] [tiquality]: [Tiquality] Remaining: 6
[22:43:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Tiquality] Remaining: 6
[22:43:48] [Server thread/INFO] [tiquality]: Importing: razorz at DIM=0 X: 2907 Z: -161
[22:43:48] [Server thread/INFO] [tiquality]: [Tiquality] Remaining: 5
[22:43:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Tiquality] Remaining: 5
[22:43:48] [Server thread/INFO] [tiquality]: Importing: justkill at DIM=0 X: 2480 Z: 849
[22:43:48] [Server thread/INFO] [tiquality]: [Tiquality] Remaining: 4
[22:43:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Tiquality] Remaining: 4
[22:43:48] [Server thread/INFO] [tiquality]: Importing: kotik_kung-fu at DIM=0 X: -2209 Z: 1873
[22:43:48] [Server thread/INFO] [tiquality]: [Tiquality] Remaining: 3
[22:43:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Tiquality] Remaining: 3
[22:43:48] [Server thread/INFO] [tiquality]: Importing: mmahokhin at DIM=0 X: 2870 Z: 264
[22:43:49] [Server thread/DEBUG] [FML]: Gathering id map for writing to world save world
[22:43:49] [Server thread/DEBUG] [enderio]: Saving ServerChannelRegister with gen=1544470530025
[22:43:49] [Server thread/DEBUG] [enderio]: ServerChannelRegister: Saving channel бес
[22:43:49] [Server thread/DEBUG] [enderio]: ServerChannelRegister: Saving channel 1
[22:43:49] [Server thread/DEBUG] [enderio]: ServerChannelRegister: Saving channel 11`

**Comment by bigenergy** [comment]
Full log
[latest.log](https://github.com/TerminatorNL/Tiquality/files/2664778/latest.log)

**Comment by TerminatorNL** [comment]
The latest.log is Tiquality 0.8.4 are you sure you have the right log/version installed?

**Comment by bigenergy** [comment]
This error is reproduced at 0.8.5, the logs are identical.

**Comment by TerminatorNL** [comment]
My best would be that that is an admin claim, I am performing some extra checks to verify it has an owner before blindly assuming the input is correct :man_facepalming: 2362319650f19c59223984b39bf00eba1b079d6b

**Comment by bigenergy** [comment]
> My best would be that that is an admin claim, I am performing some extra checks to verify it has an owner before blindly assuming the input is correct 🤦‍♂️ [2362319](https://github.com/TerminatorNL/Tiquality/commit/2362319650f19c59223984b39bf00eba1b079d6b)

the same error after /tq import_griefprevention
**0.8.8**
[new.log](https://github.com/TerminatorNL/Tiquality/files/2669417/new.log)

**Comment by bigenergy** [comment]
did you look at my error? need any details?

**Comment by TerminatorNL** [comment]
I just uploaded a new version of tiquality. Would you mind giving that a shot? Also: Let's create a new issue for new crashes :P
