### ISSUE TITLE
[Bug] Player Profile not found in cache console spam

### ISSUE THREAD

**Issue by MrNinja93** [TerminatorNL/Tiquality#40]
**Describe the bug**
Console spam by tiquality constantly attempting to add what I assume is a fake player to cache and sending profile requests to mojang which fail as the uuid doesn't seem to exist.

**To Reproduce**
In this instance the block in question always seems to be a industrial foregoing crop sower.

I'd assume having one working with tiquality installed is enough to replicate (error has been present across multiple servers/packs with the same block as cause)

**Which Forge version are you using?**
Forge 14.23.5.2838
Tiquality 1.5.5 Fat

**If you used the word 'error' somewhere, always provide the stack trace along with both _debug.log_ and _latest.log_**
Debug and Latest log
https://gist.github.com/MrNinja93/e523c8547082482e4d2a297be65b909d

**Stack Trace**

```[17:49:42] [Server thread/WARN] [tiquality]: Player profile was not found in cache!
[17:49:42] [Server thread/WARN] [tiquality]: I will add it, but it can cause some lag, as I may or may not contact the Mojang servers to get go and get it.
[17:49:42] [Server thread/WARN] [tiquality]: UUID: ec5b5875-ebb5-4b47-833b-0de37ac9e6d7
[17:49:42] [Server thread/WARN] [tiquality]: Most significant bits:  -1415440394388944057
[17:49:42] [Server thread/WARN] [tiquality]: Least significant bits: -8990576960446273833
[17:49:42] [Server thread/WARN] [mojang/YggdrasilMinecraftSessionService]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@1eeacbae[id=ec5b5875-ebb5-4b47-833b-0de37ac9e6d7,name=<null>,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [YggdrasilMinecraftSessionService.class:?]
	at cf.terminator.tiquality.util.ForgeData.getGameProfileByUUID(ForgeData.java:83) [ForgeData.class:?]
	at cf.terminator.tiquality.monitor.BlockPlaceMonitor.onBlockPlaceEvent(BlockPlaceMonitor.java:24) [BlockPlaceMonitor.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1139_BlockPlaceMonitor_onBlockPlaceEvent_PlaceEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:178) [ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:920) [ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) [aip.class:?]
	at com.buuz135.industrial.tile.agriculture.CropSowerTile.work(CropSowerTile.java:148) [CropSowerTile.class:?]
	at com.buuz135.industrial.tile.WorkingAreaElectricMachine.performWork(WorkingAreaElectricMachine.java:112) [WorkingAreaElectricMachine.class:?]
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280) [ElectricMachine.class:?]
	at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:120) [CustomElectricMachine.class:?]
	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118) [ElectricTileEntity.class:?]
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:991) [SidedTileEntity.class:?]
	at cf.terminator.tiquality.tracking.tickexecutors.ForgeTickExecutor.onTileEntityTick(ForgeTickExecutor.java:30) [ForgeTickExecutor.class:?]
	at net.minecraft.tileentity.TileEntity.tiquality_doUpdateTick(TileEntity.java:627) [avj.class:?]
	at cf.terminator.tiquality.tracking.TrackerBase.tickSimpleTickable(TrackerBase.java:217) [TrackerBase.class:?]
	at cf.terminator.tiquality.tracking.TickHub.onTileEntityTick(TickHub.java:63) [TickHub.class:?]
	at net.minecraft.world.World.redirect$onUpdateTileEntities$zzn000(World.java:5093) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1835) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]```

**Comment by TerminatorNL** [comment]
I have not personally tested the new code, but this should solve the issue. (Fake player generates errors in mojang authentication code)

If the issue persists, re-open this issue!
