### ISSUE TITLE
[Bug] After install GriefDefender - server lagged and spammed

### ISSUE THREAD

**Issue by yaroslav4167** [TerminatorNL/Tiquality#56]
**Describe the bug**
I builded and installed the griefdefender-1.5.3 and griefdefender-api, after start my server i found this bug.
Spammed messages:
```
[pool-8-thread-4/INFO] [STDERR]: [com.github.terminatornl.tiquality.world.WorldHelper$SetTrackerTask:run:278]: java.lang.ArrayIndexOutOfBoundsException: -1
[pool-8-thread-4/INFO] [STDERR]: [com.github.terminatornl.tiquality.world.WorldHelper$SetTrackerTask:run:278]:       at com.github.terminatornl.tiquality.world.ChunkStorage.set(ChunkStorage.java:70)
[pool-8-thread-4/INFO] [STDERR]: [com.github.terminatornl.tiquality.world.WorldHelper$SetTrackerTask:run:278]:       at net.minecraft.world.chunk.Chunk.tiquality_setTrackedPosition(Chunk.java:6683)
[pool-8-thread-4/INFO] [STDERR]: [com.github.terminatornl.tiquality.world.WorldHelper$SetTrackerTask:run:278]:       at com.github.terminatornl.tiquality.world.WorldHelper$SetTrackerTask.run(WorldHelper.java:270)
[pool-8-thread-4/INFO] [STDERR]: [com.github.terminatornl.tiquality.world.WorldHelper$SetTrackerTask:run:278]:       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[pool-8-thread-4/INFO] [STDERR]: [com.github.terminatornl.tiquality.world.WorldHelper$SetTrackerTask:run:278]:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[pool-8-thread-4/INFO] [STDERR]: [com.github.terminatornl.tiquality.world.WorldHelper$SetTrackerTask:run:278]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[pool-8-thread-4/INFO] [STDERR]: [com.github.terminatornl.tiquality.world.WorldHelper$SetTrackerTask:run:278]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[pool-8-thread-4/INFO] [STDERR]: [com.github.terminatornl.tiquality.world.WorldHelper$SetTrackerTask:run:278]:       at java.lang.Thread.run(Thread.java:748)
```

**Which Forge version are you using?**
1.12.2-14.23.5.2847

**Which SpongeForge version are you using?**
1.12.2-2838-7.3.1-RC4094

**Please provide the early startup messages starting with _[Tiquality-Boot]_**

```
[Tiquality-Boot]: I am located here: file:/home/logic/NewSky/./mods/(S)Tiquality-THIN-1.12.2-GAMMA-1.8.1-124.jar!/com/github/terminatornl/tiquality/Tiquality.class
[Tiquality-Boot]: I am designed for Forge version: 1.12.2-14.23.5.2847
[Tiquality-Boot]: Loading server classes
[Tiquality-Boot]: SpongeForge is present!
[Tiquality-Boot]: I am designed for SpongeForge version: 1.12.2-2838-7.1.11-RC4007
[Tiquality-Boot]: SpongeForge version is different than expected!
[Tiquality-Boot]: This could result in undefined behavior.
[Tiquality-Boot]:
[Tiquality-Boot]: Expected: '1.12.2-2838-7.1.11-RC4007', but you have: '1.12.2-2838-7.3.1-RC4094' installed.
[Tiquality-Boot]: We're running in a production environment.
```

[SpamLog](https://lww.page.link/ocJG)

**Comment by yaroslav4167** [comment]
Maybe this bug is not related to griefdefender.
Probably a problem with my world.
